"use client";

import { ArrowLeft, Camera, Check, Cloud, Database, ImagePlus, LoaderCircle, LockKeyhole, MessageCircle, Radio, Send, ShieldCheck, Sparkles, X } from "lucide-react";
import { createClient } from "@supabase/supabase-js";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import "./wall.css";

export const dynamic = "force-dynamic";

const url = String(process.env.NEXT_PUBLIC_SUPABASE_URL || "").replace(/^["']|["']$/g, "").trim();
const key = String(process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "").replace(/^["']|["']$/g, "").trim();

// To prevent Next.js from crashing during static build (SSG) if env vars are missing, we provide a valid dummy URL format.
const supabase = createClient(
  url || "https://build.supabase.co",
  key || "sb_build_placeholder"
);
type MemoryPost = { id:string; created_at:string; name:string; message:string; image_path:string|null; session_id:string };

const timeAgo=(date:string)=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(date).getTime())/1000));if(seconds<60)return"just now";const minutes=Math.floor(seconds/60);if(minutes<60)return minutes+"m ago";const hours=Math.floor(minutes/60);if(hours<24)return hours+"h ago";return new Date(date).toLocaleDateString(undefined,{day:"numeric",month:"short"})};
const extensionFor=(file:File)=>({"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif"} as Record<string,string>)[file.type];

export default function MemoryWall(){
 const [posts,setPosts]=useState<MemoryPost[]>([]),[name,setName]=useState(""),[message,setMessage]=useState(""),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[sessionId,setSessionId]=useState(""),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[connection,setConnection]=useState<"connecting"|"live"|"offline">("connecting"),[notice,setNotice]=useState<{kind:"ok"|"error";text:string}|null>(null);
 useEffect(()=>{const existing=localStorage.getItem("mranti-memory-session");const id=existing||("wall-"+crypto.randomUUID());if(!existing)localStorage.setItem("mranti-memory-session",id);setSessionId(id)},[]);
 const loadPosts=useCallback(async()=>{const {data,error}=await supabase.from("memory_wall_posts").select("id,created_at,name,message,image_path,session_id").order("created_at",{ascending:false}).limit(60);if(error){setConnection("offline");setNotice({kind:"error",text:"The wall could not load. Please try again."})}else{setPosts((data as MemoryPost[])||[]);setConnection("live")}setLoading(false)},[]);
 useEffect(()=>{loadPosts();const channel=supabase.channel("memory-wall-live").on("postgres_changes",{event:"INSERT",schema:"public",table:"memory_wall_posts"},()=>loadPosts()).subscribe(status=>{if(status==="SUBSCRIBED")setConnection("live");if(status==="CHANNEL_ERROR"||status==="TIMED_OUT")setConnection("offline")});return()=>{supabase.removeChannel(channel)}},[loadPosts]);
 useEffect(()=>{if(!file){setPreview(null);return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 const chooseFile=(next:File|null)=>{setNotice(null);if(!next){setFile(null);return}if(!extensionFor(next)){setNotice({kind:"error",text:"Use a JPG, PNG, WebP, or GIF image."});return}if(next.size>5*1024*1024){setNotice({kind:"error",text:"Keep the photo below 5 MB."});return}setFile(next)};
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!sessionId||submitting)return;const cleanName=name.trim(),cleanMessage=message.trim();if(cleanName.length<2||cleanMessage.length<1)return;setSubmitting(true);setNotice(null);let imagePath:string|null=null;if(file){const extension=extensionFor(file);if(!extension){setNotice({kind:"error",text:"That photo type is not supported."});setSubmitting(false);return}imagePath=sessionId+"/"+crypto.randomUUID()+"."+extension;const {error:uploadError}=await supabase.storage.from("memory-wall").upload(imagePath,file,{cacheControl:"3600",contentType:file.type,upsert:false});if(uploadError){setNotice({kind:"error",text:"The photo could not upload. Try a smaller image."});setSubmitting(false);return}}const {error}=await supabase.from("memory_wall_posts").insert({name:cleanName,message:cleanMessage,image_path:imagePath,session_id:sessionId});if(error)setNotice({kind:"error",text:"Your memory could not be posted. Please try again."});else{setName("");setMessage("");setFile(null);setNotice({kind:"ok",text:"Your memory is now on the wall."});await loadPosts()}setSubmitting(false)};
 const memoryCards=useMemo(()=>posts.map(post=>({...post,imageUrl:post.image_path?supabase.storage.from("memory-wall").getPublicUrl(post.image_path).data.publicUrl:null})),[posts]);
 return <main className="wall-page">
  <header className="wall-topbar"><a href="/" className="wall-back"><ArrowLeft/>Workshop</a><div className="wall-brand"><span><MessageCircle/></span>MRANTI × Supabase KL MEMORY WALL</div><div className={"wall-live "+connection}><Radio/>{connection==="live"?"Live":connection==="connecting"?"Connecting":"Offline"}</div></header>
  <section className="wall-intro"><div><span className="wall-eyebrow"><Sparkles/>ONE TINY APP · FIVE SUPABASE FEATURES</span><h1>Leave one idea<br/><em>worth remembering.</em></h1><p>Post a comment, add a photo, and watch the wall update for everyone in the room.</p></div><div className="wall-stack"><span><Database/>Database</span><span><Cloud/>Storage + CDN</span><span><ShieldCheck/>RLS policies</span><span><Radio/>Realtime</span><span><LockKeyhole/>Publishable key</span></div></section>
  <section className="wall-workspace"><aside className="wall-composer"><div className="composer-head"><span><Send/></span><div><small>ADD TO THE WALL</small><h2>Share a memory</h2></div></div><form onSubmit={submit}><label><span>Your name</span><input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={40} required placeholder="e.g. Hovah"/></label><label><span>Your MVP takeaway <i>{message.length}/280</i></span><textarea value={message} onChange={e=>setMessage(e.target.value)} minLength={1} maxLength={280} required placeholder="What idea will you take into your next build?"/></label><label className={"photo-picker "+(preview?"has-preview":"")}>{preview?<><img src={preview} alt="Selected upload preview"/><button type="button" onClick={e=>{e.preventDefault();setFile(null)}} aria-label="Remove selected photo"><X/></button></>:<div><ImagePlus/><b>Add a photo</b><small>JPG, PNG, WebP or GIF · max 5 MB</small></div>}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>chooseFile(e.target.files?.[0]||null)}/></label>{notice&&<p className={"wall-notice "+notice.kind}>{notice.kind==="ok"?<Check/>:<X/>}{notice.text}</p>}<button className="post-button" disabled={submitting||!sessionId||name.trim().length<2||!message.trim()}>{submitting?<><LoaderCircle className="spin"/>Posting…</>:<>Post to the wall <Send/></>}</button></form><footer><ShieldCheck/>RLS allows posting and reading—but not editing or deleting other memories.</footer></aside>
   <div className="memory-area"><header><div><small>LIVE FROM SUPABASE</small><h2>Community memories</h2></div><span>{posts.length} {posts.length===1?"memory":"memories"}</span></header>{loading?<div className="wall-loading"><LoaderCircle className="spin"/>Loading the wall…</div>:memoryCards.length===0?<div className="wall-empty"><Camera/><h3>Be the first memory.</h3><p>Your comment will appear here instantly.</p></div>:<div className="memory-grid">{memoryCards.map((post,index)=><article key={post.id} className={"memory-card tone-"+(index%5)}>{post.imageUrl&&<img src={post.imageUrl} alt={"Photo shared by "+post.name} loading="lazy"/>}<div><MessageCircle/><p>{post.message}</p><footer><span>{post.name.slice(0,1).toUpperCase()}</span><b>{post.name}</b><time>{timeAgo(post.created_at)}</time></footer></div></article>)}</div>}</div>
  </section>
 </main>
}
